---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: cloudlare-api-secret
  namespace: cert-manager
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secret/data/cert-manager/cloudflare-api
