---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "letsencrypt@anthonytam.me"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "cloudflare@anthonytam.me"
            apiTokenSecretRef:
              name: cloudlare-api-secret
              key: cloudflare-api-key
