---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: password-management
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.23.1
    ingress:
      main:
        enabled: true
        hosts:
          - host: "bw.tam.land"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretname: tamland-tls
            hosts:
                - bw.tam.land
    persistence:
      config:
        enabled: true
        storageClass: esxi01-storage-class
        size: 10Gi
    env:
      TZ: America/Toronto
      SIGNUPS_ALLOWED: false
      DOMAIN: "https://bw.tam.land"
      ADMIN_TOKEN: ""
