---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: password-management
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.31.1
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
    ingress:
      main:
        enabled: true
        hosts:
          - host: "bw.tam.land"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - secretName: tamland-tls
            hosts:
                - bw.tam.land
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/vaultwarden
    env:
      TZ: America/Toronto
      SIGNUPS_ALLOWED: true
      DOMAIN: "https://bw.tam.land"
      ADMIN_TOKEN: ""
