apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: immich-app
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.125.1
            envFrom: &envFrom
              - secret: immich-configuration
      machine-learning:
        containers:
          machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.124.2
            envFrom: *envFrom
      postgres:
        containers:
          postgres:
            image:
              repository: tensorchord/pgvecto-rs
              tag: pg16-v0.2.0
            envFrom:
              - secret: immich-postgres-configuration
      redis:
        containers:
          redis:
            image:
              repository: redis
              tag: 7.4.2
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 2283
      machine-learning:
        enabled: true
        controller: machine-learning
        ports:
          http:
            port: 3003
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      redis:
        enabled: true
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      app:
        enabled: true
        hosts:
          - host: photos.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
              - photos.tam.land

    persistence:
      data:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/immich/data
        globalMounts:
          - path: /usr/src/app/upload
            readOnly: false
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/immich-postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                readOnly: false
