---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-general
  namespace: database
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 17.1.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: redis-app
    global:
      storageClass: esxi01-storage-class
      auth:
        existingSecret: redis-credentials
        existingSecretPasswordKey: admin-password
    image:
      repository: bitnami/redis
      tag: 7.0.5-debian-11-r0
