---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: database
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/database/redis
