kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: esxi01-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/6318de18-2deb8348-c10b-2c59e53b51d0/"
reclaimPolicy: Retain
