---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hashicorp-vault
  namespace: secrets
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com/
      chart: vault
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 5m
  values:
    server:
      serviceAccount:
        create: true
        name: vault-app
      dataStorage:
        enabled: false
      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: vault-access-key
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: vault-access-key
          secretKey: AWS_SECRET_ACCESS_KEY 
      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "s3" {
            bucket = "k8s-vault-storage"
            region = "ca-central-1"
          }
          seal "awskms" {
            kms_key_id = "2bc6eab4-0cce-4096-87e7-17f1b8f74790",
            region = "ca-central-1"
          }
      service:
        enabled: true
        type: ClusterIP
    ui:
      enabled: true
      serviceType: ClusterIP
