apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: vpn-egress
spec:
  selectors:
    - podSelector:
        matchLabels:
          egress-gw: vpn
  destinationCIDRs:
    - "0.0.0.0/0"
  excludedCIDRs:
    - "10.200.0.0/16"
    - "10.201.0.0/16"
    - "10.202.0.0/16"
  egressGateway:
    nodeSelector:
      matchLabels:
        egress-gw-vpn: "true"
    interface: ens19