apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: egress-gateway-routes
  namespace: media
spec:
  selector:
    matchLabels:
      app: egress-gateway-routes
  template:
    metadata:
      labels:
        app: egress-gateway-routes
    spec:
      hostNetwork: true
      hostPID: false
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        egress-gw-vpn: "true"
      tolerations:
      - operator: Exists
      priorityClassName: system-node-critical
      containers:
      - name: egress-gateway-routes
        image: busybox:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        env:
          - name: FROM_PREFIX
            value: "10.200.42.0/24"
          - name: GW_IP
            value: "10.200.42.1"
          - name: IFACE
            value: "ens19"
          - name: TABLE
            value: "100"
          - name: PREF
            value: "100"
          - name: METRIC
            value: "1024"
        command:
          - /bin/sh
          - -ceu
          - |
            echo "[egress-gateway-routes] starting…"
            apply() {
              set +e
              ip link show "$IFACE" >/dev/null 2>&1 && ip link set "$IFACE" up || true

              # default route in TABLE
              if ! ip route show table "$TABLE" | grep -qE "^default via ${GW_IP} dev ${IFACE}\b"; then
                ip route replace default via "$GW_IP" dev "$IFACE" table "$TABLE" metric "$METRIC"
              fi

              # source-based rule -> TABLE
              if ! ip rule show | grep -qE "from ${FROM_PREFIX} lookup ${TABLE}"; then
                ip rule add from "$FROM_PREFIX" lookup "$TABLE" pref "$PREF"
              fi

              # sanity prints (once per apply)
              ip rule show | sed 's/^/RULE: /'
              ip route show table "$TABLE" | sed 's/^/TBL100: /'
              set -e
            }

            # first apply and then loop to re-assert (handles node reboot / cilium restart)
            apply
            while true; do
              sleep 30
              apply
            done
