---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - egress-gateway-routes.yaml # Until Talos releases Routing Tables/Policy Routes https://github.com/siderolabs/talos/issues/7184
  - egress-gateway-vpn.yaml
