apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icbm-1-pictures
  namespace: other-webapps
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  volumeName: icbm-1-pictures
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icbm-1-phone-pictures
  namespace: other-webapps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: icbm-1-phone-pictures
  storageClassName: ""