apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orcaslicer
  namespace: 3d-printing
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/orcaslicer
              tag: 2.2.0
            env:
              TITLE: Orcaslicer
              PUID: 568
              PGID: 568
              TZ: America/Toronto
    service:
      app:
        controller: app
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        hosts:
          - host: orcaslicer.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - orcaslicer.local.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/3d-printing/orcaslicer/config
        advancedMounts:
          app:
            app:
              - path: /config
      data-files:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/3d-printing/orcaslicer/data-files
        advancedMounts:
          app:
            app:
              - path: /data-files
