# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.2/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallos
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: bellamy/wallos
              tag: 2.45.2
            env:
              TZ: America/Toronto
    serviceAccount:
      create: true
      name: wallos-app
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        hosts:
          - host: wallos.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - wallos.local.tam.land
    persistence:
      database:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/wallos/db
        advancedMounts:
          app:
            app:
              - path: /var/www/html/db
      logos:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/wallos/logos
        advancedMounts:
          app:
            app:
              - path: /var/www/images/uploads/logos
