---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: space-engineers
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: space-engineers-app
    image:
      repository: registry.local.tam.land/spaceengineers/server
      tag: latest
    env:
      WINEDEBUG: "-all"
      INSTANCE_NAME: "TamLand"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    service:
      main:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "misc-sharing"
        type: LoadBalancer
        ports:
          http:
            enabled: false
          gameserver:
            enabled: true
            port: 27016
            protocol: UDP
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /appdata/space-engineers/SpaceEngineersDedicated
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/space-engineers/SpaceEngineersDedicated
      plugins:
        enabled: true
        type: custom
        mountPath: /appdata/space-engineers/plugins
        accessMode: ReadWriteOnce
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/space-engineers/plugins
      instances:
        enabled: true
        type: custom
        mountPath: /appdata/space-engineers/instances
        accessMode: ReadWriteOnce
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/space-engineers/instances
      steamcmd:
        enabled: true
        type: custom
        mountPath: /root/.steam
        accessMode: ReadWriteOnce
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/space-engineers/steamcmd
