---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: unifi-app
    image:
      repository: jacobalberty/unifi
      tag: v8.4.62
    env:
      TZ: America/Toronto
    service:
      main:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "misc-sharing"
        type: LoadBalancer
    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/unifi
