---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-general
  namespace: database
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 14.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: mariadb-app
    auth:
      existingSecret: mariadb-credentials
    primary:
      persistence:
        enabled: true
        storageClass: mariadb-nfs-manual 
    image:
      repository: bitnami/mariadb
      tag: 11.1.3
