apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-nfs-pv
spec:
  storageClassName: mariadb-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.local.tam.land
    path: "/nfs-share/mariadb/data"
