---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://external-secrets.github.io/kubernetes-external-secrets/
      chart: kubernetes-external-secrets
      version: 8.5.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: external-secrets-app
    image:
      repository: ghcr.io/external-secrets/kubernetes-external-secrets
      tag: 8.5.0