---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "homelandfarm"
  namespace: admin
spec:
  secretName: "homelandfarm-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "homeland.farm"
  dnsNames:
    - "homeland.farm"
    - "*.homeland.farm"