---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 29.0.1
      sourceRef:
        kind: HelmRepository
        name: traefik-helm
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: traefik-app
    image:
      name: traefik
      tag: v2.5.5
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
    volumes:
      - name: traefik-config
        mountPath: /etc/traefik
        type: configMap
    additionalArguments:
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
