---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 34.5.0
      sourceRef:
        kind: HelmRepository
        name: traefik-helm
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: traefik-app
    image:
      tag: v3.3.4
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        asDefault: false
        redirections:
          entrypoint:
            to: websecure
            scheme: https
            peranent: true
      websecure:
        asDefault: true
        tls:
          enabled: true
          options: "default"
    volumes:
      - name: traefik-config
        mountPath: /etc/traefik
        type: configMap
    additionalArguments:
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
    service:
      spec:
        externalTrafficPolicy: Cluster
        loadBalancerIP: 10.200.12.0
