---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        basic:
          basicAuth:
            users: ["${traefik_basic_auth_credentials_hash}"]

        localOnly:
          ipWhiteList:
            sourceRange:
              - 10.200.0.0/16
              - 10.201.0.0/16
              - 10.202.0.0/16

      routers:
        api:
          rule: "Host(`traefik.tam.land`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "localOnly@file"
