---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        basic:
          basicAuth:
            users: [""]
        localOnly:
          ipWhiteList:
            sourceRange:
              - 10.200.0.0/16
              - 10.96.0.0/11
              - 10.64.0.0/13
      routers:
        api:
          rule: "Host(`traefik.tam.land`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "localOnly@file"
