apiVersion: v1
kind: PersistentVolume
metadata:
  name: secrets-hasicorp-vault-pv
  namespace: secrets
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/secrets/vault
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube01.homeland.lan
