apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated-downloader
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: "20250125"
            env:
              CLOUDFLARE_PROXY_BYPASS: http://localhost:8000
              UID: 33
              GID: 33
              TZ: America/Toronto
          bypass:
            enabled: true
            image:
              repository: ghcr.io/sarperavci/cloudflarebypassforscraping
              tag: latest
    service:
      app:
        controller: app
        ports:
          http:
            port: 8084
    ingress:
      gui:
        enabled: true
        hosts:
          - host: getbooks.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - getbooks.local.tam.land
    persistence:
      ingest:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/media/books/import
        advancedMounts:
          app:
            app:
              - path: /cwa-book-ingest