---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitcoind
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://anthonytam.github.io/blockchain-helm-charts/helm
      chart: bitcoind
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: blockchain-charts
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: bitcoind-app
    image:
      repository: ruimarinho/bitcoin-core
      tag: "22.0"
    env:
      TZ: America/Toronto
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    service:
      main:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.2
          metallb.universe.tf/allow-shared-ip: "crypto-sharing"
        type: LoadBalancer
    persistence:
      blockchain:
        enabled: true
        exisingClaim: bitcoind-pvc
