---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitcoind
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://anthonytam.github.io/blockchain-helm-charts/helm
      chart: bitcoind
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: blockchain-charts
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: bitcoind-app
    image:
      repository: ruimarinho/bitcoin-core
      tag: "22.0"
    env:
      TZ: America/Toronto
    service:
      main:
        type: NodePort
        enabled: true
    persistence:
      blockchain:
        enabled: true
        storageClass: esxi01-storage-class
        accessMode: ReadWriteOnce
