---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitcoind
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      imagePullSecrets:
       - name: ghcr-image-pull-secret
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ghcr.io/anthonytam/bitcoind
              tag: v29.1
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        enabled: true
        controller: app
        primary: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.2
          metallb.universe.tf/allow-shared-ip: "crypto-sharing"
        ports:
          p2p:
            enabled: true
            port: 8333
            protocol: TCP
          rpc:
            enabled: true
            port: 8332
            protocol: TCP
    persistence:
      blockchain:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/crypto/bitcoind
        advancedMounts:
          app:
            app:
              - path: /app/.bitcoin
