---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bitcoind
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: bitcoind-app
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: kylemanna/bitcoind
              tag: latest
              pullPolicy: Always
            env:
              TZ: America/Toronto
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        enabled: true
        controller: app
        prinary: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.2
          metallb.universe.tf/allow-shared-ip: "crypto-sharing"
        ports:
          bitcoind:
            enabled: true
            port: 8333
            protocol: TCP
          bitcoind-rpc:
            enabled: true
            port: 8332
            protocol: TCP
    persistence:
      blockchain:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/crypto/bitcoind
        advancedMounts:
          app:
            app:
              - path: /bitcoin/.bitcoin