---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: gpu-operator
      version: v24.9.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
      interval: 5m
  values:
    driver:
      enabled: false
    nfd:
      enabled: true
    toolkit:
      enabled: true
