apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-mariadb-pv
  namespace: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/database/mariadb
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: database-mariadb-pvc 
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi
