apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-mariadb-pv
  namespace: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/database/mariadb
