---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: registry-app
    image:
      repository: registry
      tag: 2
    service:
      main:
        enabled: true
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        hosts:
          - host: registry.local.tam.land
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: local-tamland-tls
            hosts:
              - registry.local.tam.land
        
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /var/lib/registry
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/registry
