---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lubelog
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.4.5
            envFrom:
              - secret: lubelog-configuration
    serviceAccount:
      create: true
      name: lubelog-app
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8080
    ingress:
      app:
        enabled: true
        hosts:
          - host: lubelog.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
              - lubelog.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/config
        advancedMounts:
          app:
            app:
              - path: /App/config
      data:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/data
        advancedMounts:
          app:
            app:
              - path: /App/data
      translations:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/translations
        advancedMounts:
          app:
            app:
              - path: /App/wwwroot/translations
      documents:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/documents
        advancedMounts:
          app:
            app:
              - path: /App/wwwroot/documents
      images:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/images
        advancedMounts:
          app:
            app:
              - path: /App/wwwroot/images
      temp:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/temp
        advancedMounts:
          app:
            app:
              - path: /App/wwwroot/temp
      log:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/log
        advancedMounts:
          app:
            app:
              - path: /App/log
      keys:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/lubelog/keys
        advancedMounts:
          app:
            app:
              - path: /root/.aspnet/DataProtection-Keys