---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lubelog
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.3.0
            envFrom:
              - secret: lubelog-configuration
    serviceAccount:
      create: true
      name: lubelog-app
    service:
      main:
        enabled: true
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: lubelog.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - secretName: tamland-tls
            hosts:
              - lubelog.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/config
        globalMounts:
          - path: /App/config
            readonly: false
      data:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/data
        globalMounts:
          - path: /App/data
            readonly: false
      translations:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/translations
        globalMounts:
          - path: /App/wwwroot/translations
            readonly: false
      documents:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/documents
        globalMounts:
          - path: /App/wwwroot/documents
            readonly: false
      images:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/images
        globalMounts:
          - path: /App/wwwroot/images
            readonly: false
      temp:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/temp
        globalMounts:
          - path: /App/wwwroot/temp
            readonly: false
      log:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/log
        globalMounts:
          - path: /App/log
            readonly: false
      keys:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/lubelog/keys
        globalMounts:
          - path: /root/.aspnet/DataProtection-Keys
            readonly: false
