---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media-management
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: sonarr-app
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1342
    env:
      TZ: America/Toronto
    ingress:
      main:
        enabled: true
        hosts:
          - host: "sonarr.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/sonarr/config
        mountPath: /config
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/tv
        mountPath: /media
      downloads:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/complete
        mountPath: /complete