---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbootxyz
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: netboot-app
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: latest
            env:
              TZ: America/Toronto
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 3000
      assets:
        enabled: true
        controller: app
        primary: false
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "misc-sharing"
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        hosts:
          - host: netboot.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - netboot.local.tam.land
        
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/admin/netbootxyz/config
        advancedMounts:
          app:
            app:
              - path: /config
                readOnly: false
      assets:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/netboot-roots
        advancedMounts:
          app:
            app:
              - path: /assets
                readOnly: false
