---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netbootxyz
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: netboot-app
    image:
      repository: linuxserver/netbootxyz
      tag: 0.7.1
    env:
      TZ: America/Toronto
    service:
      main:
        enabled: true
        ports:
          http:
            port: 3000
      assets:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "misc-sharing"
        primary: false
        type: LoadBalancer
        ports:
          http-assets:
            enabled: true
            primary: false
            protocol: HTTP
            port: 80
      tftp:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "misc-sharing"
        primary: false
        type: LoadBalancer
        ports:
          udp-tftp:
            enabled: true
            primary: false
            protocol: UDP
            port: 69
    ingress:
      main:
        enabled: true
        hosts:
          - host: netboot.local.tam.land
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: local-tamland-tls
            hosts:
              - netboot.local.tam.land
        
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /config
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/netbootxyz/config
      assets:
        enabled: true
        type: custom
        mountPath: /assets
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/netbootxyz/assets
