---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ts3-server
  namespace: communication
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=http://charts.sandermann.cloud
      chart: teamspeak3
      version: 0.3.3
      sourceRef:
        kind: HelmRepository
        name: sandermann
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: ts3-app
    image:
      repository: teamspeak
      tag: 3.13.6
      pullPolicy: IfNotPresent
    env:
      TS3SERVER_LICENSE: accept
      TZ: America/Toronto
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: 'node01-sharing'
      type: LoadBalancer
      externalIPs:
        - 192.168.0.240
      tcp:
        enabled: true
    persistence:
      enabled: true
      storageClass: local-path
