# HelmRelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'vpn-app'
      vault.hashicorp.com/agent-inject-secret-vpn-auth.txt: 'homelab/vpn/config'
      vault.hashicorp.com/agent-inject-template-vpn-auth.txt: |
        {{- with secret "homelab/vpn/config" -}}
        {{ .Data.data.username }}
        {{ .Data.data.password }}
        {{- end -}}
    serviceAccount:
      create: true
      name: vpn-app
    settings:
      VPN_INTERFACE: tun0
      VPN_BLOCK_OTHER_TRAFFIC: false
      VPN_TRAFFIC_PORT: 1194
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      VPN_LOCAL_CIDRS: "192.168.0.0/16 172.16.0.0/24 10.0.0.0/8"
    routed_namespaces:
    - vpn