apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: vpn-credentials
  namespace: vpn-gateway
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  target:
    name: vpn-credentials
    template:
      data:
        vpn-auth.txt: |
          {{ .username | toString }}
          {{ .password | toString }}
  dataFrom:
    - secrets/data/database/postgres
