---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: smart-home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: homeassistant/home-assistant
              tag: "2024.12"
            env:
              TZ: America/Toronto
              PYTHONPATH: /config/deps
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 16.6
            envFrom: 
              - secret: homeassistant-configuration
      influxdb:
        enabled: true
        containers:
          influxdb:
            image:
              repository: influxdb
              tag: 2.7.11
    serviceAccount:
      name: homeassistant-app
      create: true
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8123
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      influxdb:
        enabled: true
        controller: influxdb
        ports:
          http:
            port: 8086
    ingress:
      app:
        enabled: true
        hosts:
          - host: "hass.tam.land"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
                - hass.tam.land
    persistence:
      appconfig:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/home-assistant/app
        advancedMounts:
          app:
            app:
              - path: /config
                readOnly: false
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/home-assistant/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                readOnly: false
      influxconfig:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/influxdb/config
        advancedMounts:
          influxdb:
            influxdb:
              - path: /etc/influxdb2
                readOnly: false
      influxdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/influxdb/data
        advancedMounts:
          influxdb:
            influxdb:
              - path: /var/lib/influxdb2
                readOnly: false
