---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: smart-home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    deployment:
    serviceAccount:
      name: hass-app
      create: true
    image:
      name: homeassistant/home-assistant
      tag: "2021.12"
    env:
      TZ: America/Toronto
    ingress:
      main:
        enabled: true
        hosts:
          - host: "hass.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/smart-home/hass/config
        mountPath: /config