---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: smart-home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    deployment:
    serviceAccount:
      name: hass-app
      create: true
    image:
      name: homeassistant/home-assistant
      tag: "2023.1"
    env:
      TZ: America/Toronto
    ingress:
      main:
        enabled: true
        hosts:
          - host: "hass.tam.land"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tamland-tls
            hosts:
                - hass.tam.land
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-pvc
        mountPath: /config
