---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
  namespace: retro-repair
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: postgresql
      version: 13.2.24
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: retro-repair-postgres-app
    auth:
      existingSecret: postgres-credentials
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
    primary:
      persistence:
        enabled: true
        existingClaim: retro-repair-postgres-nfs-pvc 
    image:
      repository: bitnami/postgresql
      tag: 16.1.0-debian-11-r14
