apiVersion: v1
kind: PersistentVolume
metadata:
  name: retro-repair-postgres-nfs-pv
spec:
  storageClassName: retro-repair-postgres-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.tam.land
    path: "/nfs-share/retro-repair-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retro-repair-postgres-nfs-pvc
  namespace: retro-repair
spec:
  storageClassName: retro-repair-postgres-nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
