apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-nfs-pv-0
spec:
  storageClassName: elasticsearch-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: truenas.local.tam.land
    path: "/mnt/main-bay/k8s-data/elasticsearch-data-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-nfs-pv-1
spec:
  storageClassName: elasticsearch-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: truenas.local.tam.land
    path: "/mnt/main-bay/k8s-data/elasticsearch-data-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-nfs-pv-2
spec:
  storageClassName: elasticsearch-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: truenas.local.tam.land
    path: "/mnt/main-bay/k8s-data/elasticsearch-data-2"
