---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: erpnext-values
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/erpnext-values
