---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: smart-home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: esphome/esphome
      tag: "2021.12.1"
    ingress:
      main:
        enabled: true
        hosts:
          - host: "esphome.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/smart-home/esphome/config
        mountPath: /config