apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: smart-home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: esphome/esphome
              tag: "2025.8.3"
            env:
              ESPHOME_DASHBOARD_USE_PING: true
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 6052
    ingress:
      app:
        enabled: true
        hosts:
          - host: "esphome.tam.land"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
                - esphome.tam.land
    persistence:
      appdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/esphome/app
        advancedMounts:
          app:
            app:
              - path: /config
                readOnly: false
