apiVersion: v1
stringData:
    values.yaml: ENC[AES256_GCM,data:IXtQ3PJKWX90P5VApc5MtaAtz0N7aqJlxdLMVfUDhARKdejbrH8zm0CJxBksEb/N5aPSLc88GQTFUoewREcSxgXFywDfUmnwvgr/8LIPDgiXSez3q5j1y091rnsLY07NUehhOEjgLy2B6NzllBiDbHb27MCtY1G8cSq4BOVjevVHgz9IvpxmOTEpCYVN62aMUnYKkheEsOx9pvB0J0G7uWUHx3V/9abTxjbfbGHXA8SraGWrcGDP7SEys456evlmTsOTrOo2e4nVrmUOslVXlg==,iv:YlRoRvA8Bp2UAgJUthrw5hX4/1y+MXhZlVvXCLxkI5g=,tag:FbwjwXYGWGrTj9DZ3X65nA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: proxmox-csi-sops-secrets
    namespace: csi-proxmox
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T00:58:27Z"
    mac: ENC[AES256_GCM,data:jW81Cpe+ql48C6ctvQ3UWKuXPnx73HqF150HsV6YcCbe8UPpSJkyOWoFhKz8PjGHy7XJ7nAN+kx63D5lDg+s68LsOr6WvQvGFOKK2yhf7d6hRMM4mkQ0ja4kln47XD0fgEYgHpoO4lz88rr9l5iecg9TPdVu6uC2wTrcBnWkGrw=,iv:TtUocP6XV4enspR+5jB73c70zGTwl95F/NMCZr1c3uU=,tag:HiafANg5ZOBEWPNaeGlN9A==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
