apiVersion: v1
stringData:
    values.yaml: ENC[AES256_GCM,data:IXtQ3PJKWX90P5VApc5MtaAtz0N7aqJlxdLMVfUDhARKdejbrH8zm0CJxBksEb/N5aPSLc88GQTFUoewREcSxgXFywDfUmnwvgr/8LIPDgiXSez3q5j1y091rnsLY07NUehhOEjgLy2B6NzllBiDbHb27MCtY1G8cSq4BOVjevVHgz9IvpxmOTEpCYVN62aMUnYKkheEsOx9pvB0J0G7uWUHx3V/9abTxjbfbGHXA8SraGWrcGDP7SEys456evlmTsOTrOo2e4nVrmUOslVXlg==,iv:YlRoRvA8Bp2UAgJUthrw5hX4/1y+MXhZlVvXCLxkI5g=,tag:FbwjwXYGWGrTj9DZ3X65nA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: proxmox-csi-sops-secrets
    namespace: csi-proxmox
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:09:33Z"
    mac: ENC[AES256_GCM,data:N1OUWf1iYw2YWAOxm+Hncm/2fOait/2Aw2T1RXDiVZkuKPpWdZkUQF5m0XW3tpnG1m222qSO0LqMGK9e/+WtUyf7GyDEK0qdp3f2aAhdKseXyGIxdmhrTK8S8lna45xPsaoIBFmgTPM0mj664YJ/lKhB04bJVZVUzBXZZzIyovU=,iv:Lj+3q6986b7ijMaEeLhflUoY3+bpdTdWQ7M4t0e5Sg8=,tag:T0ZXkTlPsmwPi+vkHV+kEw==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
