---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-staging
  namespace: homerow
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: wordpress
      version: 15.2.22
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: "homerow-mysql-app"
    image:
      repository: bitnami/wordpress
      tag: 5.8.3-debian-10-r2
    wordpressUsername: ${wordpress_username}
    wordpressPassword: ${wordpress_password}
    wordpressEmail: ${wordpress_email}
    wordpressFirstName: ${wordpress_first_name}
    wordpressLastName: ${wordpress_last_name}
    wordpressBlogName: ${wordpress_blog_name}
    wordpressPlugins: all
    ingress:
      enabled: true
      hostname: staging.homerow.ca
    service:
      type: ClusterIP
    persistence:
      existingClaim: wordpress-staging-pvc
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql.homerow.svc.cluster.local
      user: ${mysql_user}
      database: ${mysql_database}
      password: ${mysql_password}