---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-staging
  namespace: homerow
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: wordpress
      version: 12.3.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: "homerow-mysql-app"
    image:
      repository: bitnami/wordpress
      tag: 5.8.3-debian-10-r2
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: 'node01-sharing'
    mariadb:
      enabled: false