apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-wordpress-pv
  namespace: homerow
spec:
  claimRef:
    name: wordpress-staging-pvc
    namespace: homerow
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/homerow/wordpress
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-staging-pvc
  namespace: homerow
spec:
  storageClassName: ""
  volumeName: data-wordpress-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
