apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zabbix-postgres
  namespace: monitoring
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        serviceAccount:
          identifier: zabbix-postgres-app
        containers:
          app:
            image:
              repository: postgres
              tag: 16.9
            envFrom: 
              - secret: zabbix-postgres-configuration
    serviceAccount:
      zabbix-postgres-app: {}
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 5432
    persistence:
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/monitoring/zabbix/postgres
        advancedMounts:
          app:
            app:
              - path: /var/lib/postgresql/data
                readOnly: false
