---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: zabbix-postgres-configuration
  namespace: monitoring
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/monitoring/zabbix
