---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hashicorp-vault
  namespace: secrets
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://anthonytam.github.io/Chia-Forks-Docker/helm
      chart: vault
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 5m
  values:
    server:
      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "file" {
            path = "/vault/data"
          }
      service:
        enabled: true
        type: ClusterIP
        externalIPs:
          - "192.168.0.155"
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: null
        accessMode: ReadWriteOnce
    ui:
      enabled: true
      serviceType: ClusterIP
