---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media-management
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: radarr-app
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.2.2.5080
    env:
      TZ: America/Toronto
    service:
      main:
        enabled: true
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        hosts:
          - host: "radarr.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/radarr/config
        mountPath: /config
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/movies
        mountPath: /media
      downloads:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/complete
        mountPath: /complete