apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spoolman
  namespace: 3d-printing
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/donkie/spoolman
              tag: 0.22.1
            env:
              TZ: America/Toronto
    service:
      app:
        controller: app
        ports:
          http:
            port: 8000
    ingress:
      app:
        enabled: true
        hosts:
          - host: spoolman.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - spoolman.local.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/3d-printing/spoolman/data
        advancedMounts:
          app:
            app:
              - path: /home/app/.local/share/spoolman
