---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: k8s-sigs
        namespace: flux-system
      interval: 5m
  values:
    nfs:
      server: nfs.local.tam.land
      path: /nfs-share/admin/nfs-provisioner
    storageClass:
      create: true
      defaultClass: true
      name: nfs-provisioner-ssd