apiVersion: v1
stringData:
    cloudflare-api-key: ENC[AES256_GCM,data:VmPrDfSA0w8cUae38F4G4sOHhkNr5Jie+2ReKxu+EgG8OaUGc5wtMA==,iv:7p58G6k7aqVeqJn2JA4/0GhfF+VECdpDcPHbmizFXhQ=,tag:v0qVIKaV7j0m7f+CdKqbnA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-api-secret
    namespace: cert-manager
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:58:50Z"
    mac: ENC[AES256_GCM,data:aps0w7gswgX54O8ro8K5zF2Z61jxeUk13+dy7PdMnVg+s6Yb6asDViv/n55hGM+hnUDE7oTgVnrbjUAv0i2mLFQu8I8ssaJ2GigAsrOMOFuH2Gvdj/thWLKCzxgQq3I8yOMfqqUsS31j8aMIvkEqPUGu1y492B+YHn57HkdbgdA=,iv:TvaKHqxK9UaXGBxUJ6DRGbyMi9h7HolmP1MrbRfS1Lo=,tag:wADYWf1hvizkyZYkjlRD7w==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.1
