---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'torrent-app'
      vault.hashicorp.com/agent-inject-secret-vpn-auth.txt: 'homelab/vpn/config'
      vault.hashicorp.com/agent-inject-template-vpn-auth.txt: |
        {{- with secret "homelab/vpn/config" -}}
        {{ .Data.data.username }}
        {{ .Data.data.password }}
        {{- end -}}
    serviceAccount:
      create: true
      name: torrent-app
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.7
    settings:
      automaticPortSetup: true
    env:
      TZ: America/Toronto
      WAIT_FOR_VPN: true
    service:
      main:
        enabled: true
      bittorent:
        enabled: true
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/qbittorrent
      media:
        enabled: false
        size: 10Gi
        storageClass: null
        accessMode: ReadWriteOnce
      downloads:
        enabled: false
        size: 10Gi
        storageClass: null
        accessMode: ReadWriteOnce
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared