apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      labels:
        egress-gw: vpn
    #   dnsConfig:
    #     options:
    #       - name: ndots
    #         value: "1"
    controllers:
      app:
        enabled: true
        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.11
            restartPolicy: Always
            securityContext:
              runAsUser: 0
              runAsGroup: 0
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: 5.1.2
            env:
              PUID: 568
              PGID: 568
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8080
    ingress:
      app:
        enabled: true
        hosts:
          - host: qbittorrent.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - qbittorrent.local.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/media/qbittorrent/config
        advancedMounts:
          app:
            app:
              - path: /config
                readOnly: false
      media:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/media
        advancedMounts:
          app:
            app:
              - path: /media
                readOnly: false
      dnsdist:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/media/dnsdist
        advancedMounts:
          app:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true