---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wikijs-home
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: wikijs
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: wikijs-home-app
    image:
      repository: linuxserver/wikijs
      tag: 2.5.300
    env:
      TZ: America/Toronto
    envFrom:
      - secretRef:
          name: wikijs-home-credentials
    ingress:
      main:
        enabled: true
        hosts:
          - host: wikihome.tam.land
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tam.land-tls
            hosts:
              - wikihome.tam.land
    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/wikijs-home
