apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikijs-nfs-pv
spec:
  storageClassName: wikijs-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.tam.land
    path: "/nfs-share/wikijs-home"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-nfs-pvc
  namespace: other-webapps
spec:
  storageClassName: wikijs-nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
