apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: wikijs-home-credentials
  namespace: other-webapps 
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/other-webapps/wikijs
