apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:RL4GY6MTNN1s4UM=,iv:TSyaJ0yMi2Rt/Ex/T0P3yeipWSsNxGH93eQ3RCmagfg=,tag:iZ/0F5Jtbk4zEwHHpu2Xxg==,type:str]
    password: ENC[AES256_GCM,data:sgsX2iSAqTfVO7I3UiLUnKqcQa99tSBO4t0sdvTQ1KuUC/lLDsCYHnPH3JOfBJFFplEke7dMTocEhzvsYHIltqW153X29BQRyOIGKcpg8ua97RwDgsp/Zg7TyyZmUQz86sbwCI7y45opSugUeENPIDeREsm9JYS5hZhKqZFr3Ck=,iv:2UPDA2MSbcN8f5iyoTSPN9QXZh1e7L4YQ4pYIr0z2Jk=,tag:IajtHFpt2m6jYHfjcK8Pyg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: icbm-1-csi-secret
    namespace: csi-smb
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-04-26T19:18:16Z"
    mac: ENC[AES256_GCM,data:USyHNSw2NFOIsMUhyjh7F9ewuMgJCozq4038NyGACbet/UG7ToRKYEctbkqcnhbq7hbCb/wofe+HcTV554p8SN/oE+feBXx8xBZ5waW5APTMMn3tB0e96USDQXO3GoDs+jDQVzi9hlzy2XQl35h6rOvZY3N88t0B0xkmk9VOitk=,iv:RE2KDBcWikGleyorPDab0ieDmRn+ja1Njxh0fXXS+J8=,tag:4bJYLV0vwJfwoEc798v2kg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
