---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mediawiki
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.2-0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: mediawiki
              tag: 1.41.0
    serviceAccount:
      create: true
      name: mediawiki-app
    service:
      main:
        enabled: true
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        hosts:
          - host: house.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - secretName: tam.land-tls
            hosts:
              - house.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/mediawiki/config
        advancedMounts:
          main:
            main:
              - path: /var/www/html/LocalSettings.php
                readOnly: false
                subPath: LocalSettings.php
      images:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/mediawiki/images
        globalMounts:
          - path: /var/www/html/images
            readonly: false
