apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluidd
  namespace: 3d-printing
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/fluidd-core/fluidd
              tag: v1.32.0
    service:
      app:
        controller: app
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        hosts:
          - host: fluidd.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - fluidd.local.tam.land
