apiVersion: v1
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:kCQzotqHB89ZCDyUiQ==,iv:Xs1Wh0zUTGjmmYsMqjn9u1iuf5/KWTDqpywZSojqNJY=,tag:3M+sae5ReZ5JqKl3fFDwMA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:BeFEOH8ThToyyUTwlA==,iv:UXt0qhTGcQYz9kJZgltGXC/fDPG/C2Rg/EH1DRbcWqU=,tag:yoEQiXadRSsJC3Ml6NH5og==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9pqSjsKkJIQ0CtLXj+cc+JruoCvzJ39mtQcLg36w6+Y=,iv:ym948AUh4p+W0tRFL2Khf6CYK1KcgTsSErPxo9fmJCw=,tag:YBO8TtamjjQLoNr6OrDZBw==,type:str]
    PGDATA: ENC[AES256_GCM,data:DKOcXYXV5lIqu6oFhriqFKW81i/rQKwB9s0G8CUTaxv6QoXp,iv:dVKJ7C/4BR/x8IOYn3Xw8U73wNuzpOgzosiD7tt6PVk=,tag:fIlrvaTLQrFs/Ahz11Jd/g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sparkyfitness-postgres-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:16:08Z"
    mac: ENC[AES256_GCM,data:dmoy+6yJvTk0hxR6Zr0yumWLEyFbBB38GpPGc/gdD1LcQ6Q+UfQ3W3BJfnUkxJAq/d9EFYK2xFkWxEn1Ivhg/VSmj2Bzw3dyMWI/wPEUzDzvM+aOazr4aPRJtGUBdTFSEfbCsK1b8HdbkM9T4lRqM0Dau1fXCcDPIohKmOZ7hb8=,iv:TXLYILEZk5qgnsKJ2w75jZY+g4QjPXrCbyesmv+AWic=,tag:vznwmGbGY8wUeozXD7/vbQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
