apiVersion: v1
stringData:
    SPARKY_FITNESS_FRONTEND_URL: ENC[AES256_GCM,data:c2SXsDEAI7Ak6jdCdfQlP2YNN+A2H2XkzyS0pgsu,iv:evJ/jPdK3y0L9cV3ymiorv7VOQ3XNTREyJdKFt2e1R0=,tag:awP/eKEopOfY9S1/mhZuew==,type:str]
    SPARKY_FITNESS_SERVER_HOST: ENC[AES256_GCM,data:x0gRKRBkLncwoeznoABWs3NU+0CwQlGZJEKEP+YOfQsWrUf4iky3d8o6RAEpEcpKg5zcLA==,iv:kIZNAGnAoTKeQM7v9pprLQpEKnudfXmyGxn/BmPz8V4=,tag:w+owy8MNieD7sAZN3pyp2g==,type:str]
    SPARKY_FITNESS_SERVER_PORT: ENC[AES256_GCM,data:hmJ6JA==,iv:9IjDcLM76Yi534XXfbmd0p/v5ky2KSXEEzmNFMizulE=,tag:JNxReNdTzKdtar32mRVOLg==,type:str]
    PUID: ENC[AES256_GCM,data:mzHc,iv:NQLhkHju6jk3l6XXsdHBOYmFatpUJ9GejQLsmuZ/9f4=,tag:EEGOhy0kBLM7cw0HzSW3hg==,type:str]
    GUID: ENC[AES256_GCM,data:gOvJ,iv:hVvv2lo0biptyaJyBYlI9xmUgNGM9fyryxIF9em1oLM=,tag:3bXjseCQjmp8kqy/o+uNVA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sparkyfitness-frontend-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:03:20Z"
    mac: ENC[AES256_GCM,data:ZzuDslKqNtxZTzd8BJDIJIOufd3eeoAeBkwHKWG0YUGzXc1vuHQIxPUHs/YJSawfysyyASLXfrZ/bvYnrDaSoS1FU7MWcLmYpg0kaGDHJ5IvZyYsEggkUujYgsCsRVFGvTQXGn/plP/TJy3rMfFYi/Z2yNPJOpdD2iN3dyv3l8I=,iv:Km/O/LTebDYtKdyRuJPISQeihR4mdyh+Kcl7pLTJpfM=,tag:tNnUEsDerC6KV4P4Imas8w==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
