apiVersion: v1
stringData:
    SPARKY_FITNESS_FRONTEND_URL: ENC[AES256_GCM,data:c2SXsDEAI7Ak6jdCdfQlP2YNN+A2H2XkzyS0pgsu,iv:evJ/jPdK3y0L9cV3ymiorv7VOQ3XNTREyJdKFt2e1R0=,tag:awP/eKEopOfY9S1/mhZuew==,type:str]
    SPARKY_FITNESS_SERVER_HOST: ENC[AES256_GCM,data:x0gRKRBkLncwoeznoABWs3NU+0CwQlGZJEKEP+YOfQsWrUf4iky3d8o6RAEpEcpKg5zcLA==,iv:kIZNAGnAoTKeQM7v9pprLQpEKnudfXmyGxn/BmPz8V4=,tag:w+owy8MNieD7sAZN3pyp2g==,type:str]
    SPARKY_FITNESS_SERVER_PORT: ENC[AES256_GCM,data:pHeXTw==,iv:JcypwUCMkH87J2G5dYWn65F3bix5+oMXzNdznPZkbME=,tag:8RPpf6kCtzJi3ZOb1Y8XlQ==,type:int]
    PUID: ENC[AES256_GCM,data:oxU8,iv:ZOrOATGNhBV0WST3Bd2adIlmGU3SlMH3u915UfOolJ0=,tag:c01xPc5qCuGv6WGebKhXCQ==,type:int]
    GUID: ENC[AES256_GCM,data:cTUO,iv:gqXrYB1BLQNQROFg2voiaA1HmLniDot2TpXvC72V0bI=,tag:VXYbG8nZ9rWZWvQKXfWVaw==,type:int]
kind: Secret
metadata:
    creationTimestamp: null
    name: sparkyfitness-frontend-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T00:52:08Z"
    mac: ENC[AES256_GCM,data:C4B3Eo6XLSJntxr/WyqTSGI1T/Gjv4k/AuaZW1waPsezCix87FF7Yk/FikUJw7mlVNLY4R1Fk9h+N21UjFdWurpIjN6JTlVzqzKo1doZMp9427JL9ChU9bfm5oTgwL7zaPFx0VIi6XNhqWoRkprG/8RlVEioWh+xkkkatw4aCe0=,iv:ONVEG3AiHagHXt/j9NjzckiOBqS4c0trnossYvZSK8g=,tag:Ln36w0H4M4Dk2wA1+CM4+w==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
