apiVersion: v1
stringData:
    SPARKY_FITNESS_DB_USER: ENC[AES256_GCM,data:L2v9ok5+t+HVQlFfvA==,iv:yVdrYZIdd4+2q1pJwplDEUNdKLnsiUct5Xt3rPycUA0=,tag:c+6nFkqdK+5JQeDLe7KiEw==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:pDmFTWRe/7hh2soQr1q1Pn3032I5FZc5b3uqBT36sBw=,iv:JEov0Ty+YZ0zuC0uKEGVxH0wwY2ufUkyLSuFqbYTTe4=,tag:X1LOVLkyCiAmoNSA+WCEJA==,type:str]
    SPARKY_FITNESS_DB_NAME: ENC[AES256_GCM,data:EfDdSaPtC1OWl0GnfA==,iv:0hiSWwSMfVarLJAx/+STeCZg92FzWNGlgLIFbUy7FuI=,tag:n4ijY4JFPSXJGKoascFPxw==,type:str]
    SPARKY_FITNESS_DB_HOST: ENC[AES256_GCM,data:Y0VV1/qjJk1DA/nnAN7PvTzwMBNRmKEv51EgXvZtm4E72rYAn5A2ZA6x2z47AQWDJZjV77K9,iv:1Up3HFY3VPo1L8Rn0LGLZI5wV8ei/7nGLZskVSrhWR0=,tag:jIq135kPgERMrvgmv9jk4w==,type:str]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:VKGZumgA87KIuY5TXPQVEDI=,iv:3hs+oQjtn1oiCSIU+GAjZ5/xmp1TmE0BQTmjWL/kNh4=,tag:77SzLPleKpffytiO5LC19g==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:jXigJnf3m0azQv0qXf1dVpiWNTPC6N71IgiKaQxJlkA=,iv:e1CL6p7ZzV08f3/X6LT6z7qFCbiqYzUsylsB4t4EJvA=,tag:+h1dvFoiNpWv0nAwKnyM3g==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:eysftlOdUV/t3EVRlOxdkna5Efn4i7TQgNyQEW7Zbw672TkpoN0qywDEldVbZRUfBigHDXq1Mf4erHh3VjiXIg==,iv:cTOLEl8FcfXz31/p7YyGWbsvz/N1PprXmgGYjPSVm7s=,tag:CQUEkydQGPXm6B8Emsfyiw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:wmYPM8Fhp0ZxBwnSstUiqbKMahLSG93W7pNKIFHM8KjleyqJQpBAnh28dZ3Fhx22CfDv213fsgikHBnOmnJLidHOtcsk2ehkRjOV7LbSFKTqqHp2FUdPYawEfpirA+jDupLR1PRISbQxlm6T2/fLI12XxfBmE9skmYXGc3xllC8=,iv:0jG21zrEkC5BeQ7nqdwv79dCrVC18mgoKTVjw0j5lMk=,tag:gGh0RCSWv4pe6IuS7fz5lA==,type:str]
    SPARKY_FITNESS_FRONTEND_URL: ENC[AES256_GCM,data:c2SXsDEAI7Ak6jdCdfQlP2YNN+A2H2XkzyS0pgsu,iv:evJ/jPdK3y0L9cV3ymiorv7VOQ3XNTREyJdKFt2e1R0=,tag:awP/eKEopOfY9S1/mhZuew==,type:str]
    SPARKY_FITNESS_DISABLE_SIGNUP: ENC[AES256_GCM,data:Y5hAjsU=,iv:zIQYvoRCl3w9HZXjaPB2gJ59cw5mNZw39V4s+GVmkV4=,tag:1vn0ymLic5x2WaZgtwPHXw==,type:bool]
    SPARKY_FITNESS_ADMIN_EMAIL: ENC[AES256_GCM,data:BhlfotSnQWdbu3OZ+hz1opI=,iv:jEITLMWXO44komR7do+EaJayu6fr5jQOEh7BTPABCdA=,tag:Apvhn1XneVNSMzrBk7yDMg==,type:str]
    TZ: ENC[AES256_GCM,data:0f0tVoNArIQ4WbXJvh5H,iv:Nz0UrCstOV+TvC8kKgLqquRgAP9mp7Q5DyXCkgRPt0M=,tag:LewmUtP07YrlX9A9yTFxXQ==,type:str]
    PUID: ENC[AES256_GCM,data:ZKLB,iv:SjoCu4IZoH2vTRFlpOEs/dBcHqpB2WUidlqLZFn4WVg=,tag:I7ycapWslLFgLWMObSL3Yg==,type:str]
    GUID: ENC[AES256_GCM,data:rzF2,iv:0bnQ0hhlQQYN13B9oCMGM7/LI4Bs6ebvbVmIyEG1X28=,tag:B54fIEoE+ldzTV8ntU0SAQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sparkyfitness-server-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:03:31Z"
    mac: ENC[AES256_GCM,data:IkOvPwg3NtMgkAyv8I/opP/qAZQg9AW9XN1GWenYYG/T3+Jt31UDSK2iHM4FxjrqIfva7vb0sLhJydo2N2GkYiLo1+/x8+/gy+oI25ujyMgQcpEUnhPE4euJ6Yvvxw0Zr52CApVeg3WaXQENtf7m3HURQisn2S0vusc3oP6muco=,iv:AAprvW/r/uU/OxUal9yxxe2n5UOgyiUX7pZZl1dmmNQ=,tag:p2srO9J2qK8c4UObt4+KOg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
