apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: frooodle/s-pdf
              tag: 0.46.1
    serviceAccount:
      create: true
      name: stirlingpdf-app
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8080
    ingress:
      app:
        enabled: true
        hosts:
          - host: pdf.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
              - pdf.tam.land
