apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ollama/ollama
              tag: 0.7.0
            env:
              NVIDIA_VISIBLE_DEVICES: all
              OLLAMA_KEEP_ALIVE: 24h
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: extensions.talos.dev/nonfree-kmod-nvidia-production
                      operator: Exists
      webui:
        enabled: true
        containers:
          webui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.10
            env:
              OLLAMA_BASE_URLS: http://ollama.other-webapps.svc.cluster.local:11434
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 11434
      webui:
        enabled: true
        controller: webui
        ports:
          http:
            port: 8080
    ingress:
      api:
        enabled: true
        hosts:
          - host: aiapi.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - aiapi.local.tam.land
      webui:
        enabled: true
        hosts:
          - host: aiui.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: webui
        tls:
          - secretName: local-tamland-tls
            hosts:
              - aiui.local.tam.land
    persistence:
      ollama:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/ollama/data
        advancedMounts:
          app:
            app:
              - path: /root/.ollama
                readOnly: false
      webui:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/ollama/webui
        advancedMounts:
          webui:
            webui:
              - path: /app/backend/data
                readOnly: false
