---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync
  namespace: secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sync
  namespace: secrets
subjects:
- kind: ServiceAccount
  name: secret-sync-app
  namespace: secrets
roleRef:
  kind: ClusterRole
  name: secret-sync
  apiGroup: rbac.authorization.k8s.io
