apiVersion: homerow.ca/v1
kind: SyncSecret
metadata:
  name: ghcr-image-pull-secret
spec:
  secret:
    name: ghcr-image-pull-secret
    namespace: small-indie-bot
  destinationNamespaces:
    - crypto