apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secret-sync
  namespace: secrets
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: secret-sync
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mss
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/mulan-szechuan-sauce/sercet-sync
      tag: 0.1.2
    crds:
      enabled: true
