---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: secret-sync
  namespace: secrets
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: secret-sync-app
    image:
      repository: registry.local.tam.land/secret-sync/sync
      tag: latest
    env:
      VAULT_ENABLED: true
      VAULT_ADDRESS: http://hashicorp-vault.secrets.svc.cluster.local:8200
      VAULT_ROLE: secret-sync-role
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: false
