---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bot
  namespace: small-indie-bot
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: small-indie-bot-app
    image:
      repository: registry.local.tam.land/small-indie-bot/bot
      tag: latest
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /config
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/small-indie-bot-bot/config
