---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: bot-environments
  namespace: small-indie-bot
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/small-indie-bot/bot
