---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: retro-repair
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 11.5.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: retro-repair-mariadb-app
    auth:
      existingSecret: mariadb-credentials
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-nfs-pvc 
    image:
      tag: 10.10.3-debian-11-r12
