apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/radarr
              tag: 5.18.4
            env:
              PUID: 568
              PGID: 568
              TZ: America/Toronto
    service:
      app:
        controller: app
        ports:
          http:
            port: 7878
    ingress:
      app:
        enabled: true
        hosts:
          - host: radarr.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - radarr.local.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/media/radarr/config
        advancedMounts:
          app:
            app:
              - path: /config
      media:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/media/
        advancedMounts:
          app:
            app:
              - path: /media
