---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: factorio-configuration
  namespace: games
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/games/factorio
