---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: factorio
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: factorio-server-charts
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: factorio-helm
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "factoriotools/factorio"
      tag: 1.1.104
    service:
      type: LoadBalancer
      port: 34197
    strategy:
      type: Recreate
    persistence:
      enabled: true
      dataDir:
        Size: "20Gi"
      storageClassName: factorio-nfs-manual

    mods:
      enabled: true
      portal:
        - aai-containers
        - bobinserters
        - BottleneckLite
        - DiscoScience
        - even-distribution
        - flib
        - "Flow Control"
        - GUI_Unifyer
        - helmod
        - HelmodAddonRequester
        - informatron
        - jetpack
        - Krastorio2
        - Krastorio2Assets
        - FNEI
        - LTN_Combinator_Modernized
        - LogisticTrainNetwork
        - LtnManager
        - rso-mod
        - RitnLib
        - "Squeak Through"
        - VehicleSnap
        - Waterfill_Fork

    factorioServer:
      save_name: "WenKrast"
      generate_new_save: true
      update_mods_on_start: true
      load_latest_save: true

    import_save:
      enabled: false

    account:
      accountSecret: factorio-account

    serverPassword:
      passwordSecret: factorio-server-password

    server_settings:
      name: WenKrast
      # Your Instance Description
      description: "Wen we Krast??"
      tags:
      - game
      - tags
      max_players: 0
      visibility:
        public: false
        lan: true
      require_user_verification: true
      max_upload_in_kilobytes_per_second: 0
      max_upload_slots: 5
      minimum_latency_in_ticks: 0
      ignore_player_limit_for_returning_players: false
      allow_commands: true
      autosave_interval: 5
      autosave_slots: 20
      afk_autokick_interval: 15
      auto_pause: true
      only_admins_can_pause_the_game: false
      autosave_only_on_server: true
      non_blocking_saving: true
      minimum_segment_size: 25
      minimum_segment_size_peer_count: 20
      maximum_segment_size: 100
      maximum_segment_size_peer_count: 10

    # Password and port for the rcon service
    rcon:
      external: true
      type: LoadBalancer
      serviceAnnotations:

      passwordSecret: factorio-rcon-password
      port: 27015

    admin_list:
      - "atam"
