---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: factorio
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: factorio-server-charts
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: factorio-helm
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "factoriotools/factorio"
      tag: 2.0.72

    service:
      type: LoadBalancer
      port: 34197
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.200.12.1
        metallb.universe.tf/allow-shared-ip: "misc-sharing"

    strategy:
      type: Recreate

    persistence:
      enabled: true
      dataDir:
        Size: "20Gi"
        existingClaim: factorio-nfs-pvc
      storageClassName: factorio-nfs-manual

    mods:
      enabled: true
      portal:
        - bobinserters
        - BottleneckLite
        - DiscoScience
        - even-distribution
        - flib
        - Flow%20Control
        - GUI_Unifyer
        - helmod
        - HelmodAddonRequester
        - informatron
        - jetpack
        - Krastorio2
        - Krastorio2Assets
        - FNEI
        - LTN_Combinator_Modernized
        - LogisticTrainNetwork
        - LtnManager
        - rso-mod
        - RitnLib
        - Squeak%20Through
        - VehicleSnap
        - Waterfill_Fork
        - Updated_Construction_Drones
        - Roboport64

    factorioServer:
      save_name: "WenKrast"
      generate_new_save: true
      update_mods_on_start: true
      load_latest_save: true

    import_save:
      enabled: true
      reimport_on_change: true

    account:
      accountSecret: factorio-configuration

    serverPassword:
      passwordSecret: factorio-configuration

    server_settings:
      name: WenKrast
      # Your Instance Description
      description: "Wen we Krast??"
      tags:
      - game
      - tags
      max_players: 0
      visibility:
        public: false
        lan: true
      require_user_verification: true
      max_upload_in_kilobytes_per_second: 0
      max_upload_slots: 5
      minimum_latency_in_ticks: 0
      ignore_player_limit_for_returning_players: false
      allow_commands: admins-only
      autosave_interval: 5
      autosave_slots: 20
      afk_autokick_interval: 15
      auto_pause: true
      only_admins_can_pause_the_game: false
      autosave_only_on_server: true
      non_blocking_saving: true
      minimum_segment_size: 25
      minimum_segment_size_peer_count: 20
      maximum_segment_size: 100
      maximum_segment_size_peer_count: 10

    rcon:
      external: true
      type: LoadBalancer
      serviceAnnotations:
        metallb.universe.tf/loadBalancerIPs: 10.200.12.1
        metallb.universe.tf/allow-shared-ip: "misc-sharing"
      passwordSecret: factorio-configuration
      port: 27015

    admin_list:
      - "atam"
      - "FlyingSeahorse"

    #Krastorio2 settings
    map_gen_settings:
      autoplace_controls:
        coal:
          frequency: 1
          size: 1
          richness: 1
        stone:
          frequency: 1
          size: 1
          richness: 1
        copper-ore:
          frequency: 1
          size: 1
          richness: 1
        iron-ore:
          frequency: 1
          size: 1
          richness: 1
        uranium-ore:
          frequency: 1
          size: 1
          richness: 1
        crude-oil:
          frequency: 1
          size: 1
          richness: 1
        trees:
          frequency: 1
          size: 1
          richness: 1
        enemy-base:
          frequency: 1
          size: 1
          richness: 1
