apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-nfs-pv
spec:
  storageClassName: factorio-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.tam.land
    path: "/nfs-share/factorio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-nfs-pvc
  namespace: games
spec:
  storageClassName: factorio-nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
