---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: homerow
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mysql
      version: 9.4.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: "homerow-mysql-app"
    auth:
      rootPassword: ${mysql_root_password}
      database: ${mysql_database}
      username: ${mysql_user}
      password: ${mysql_password}
    image:
      repository: bitnami/mysql
      tag: 8.0.27-debian-10-r78
    primary:
      persistence:
        existingClaim: data-mysql