---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: homerow
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mysql
      version: 8.8.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: "homerow-mysql-app"
    image:
      repository: bitnami/mysql
      tag: 8.0.27-debian-10-r78
    primary:
      livenessProbe:
        enabled: false
      readinessProve:
        enabled: false
      startupProbe:
        enabled: false
