---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mysql
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-app
  dataFrom:
    - homelab/data/secrets/cloudflare-api