apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql
  namespace: homerow
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "local-path"