---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lazylibrarian
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lazylibrarian
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: lazylibrarian-app
    image:
      repository: linuxserver/lazylibrarian
      tag: version-c9a09c84
    env:
      TZ: America/Toronto
      PUID: "568"
      PGID: "1001"
    ingress:
      main:
        enabled: true
        hosts:
          - host: "library.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/other/lazylibrarian/config
      media:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/other/lazylibrarian/media
