apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-magento-mariadb
  namespace: homerow
spec:
  storageClassName: "local-path"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
