apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-magento-elasticsearch-data-pv
  namespace: homerow
spec:
  claimRef:
    name: data-magentostaging--elasticsearch-data-0
    namespace: homerow
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/homerow/magento-elasticsearch-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-magentostaging--elasticsearch-data-0
  namespace: homerow
spec:
  storageClassName: "local-storage"
  volumeName: data-magento-elasticsearch-data-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
