apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-magento-pv
  namespace: homerow
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/homerow/magento
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube01