# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.2/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: small-indie-bot
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: influxdb
              tag: 2.7.11
    serviceAccount:
      create: true
      name: small-indie-bot-influxdb-app
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8086
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/small-indie-bot/influxdb/config
        advancedMounts:
          app:
            app:
              - path: /etc/influxdb2
                readOnly: false
      data:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/small-indie-bot/influxdb/data
        advancedMounts:
          app:
            app:
              - path: /var/lib/influxdb2
                readOnly: false
