---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chia-blockchain
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://anthonytam.github.io/Chia-Forks-Docker/helm
      chart: chia-blockchain
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: chia-forks
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      key:
        enabled: false
      blockchain:
        enabled: false
