apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: small-indie-bot
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
