apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: small-indie-bot
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-container
          image: doughgle/kafka-kraft
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: REPLICAS
              value: '3'
            - name: SERVICE
              value: kafka-svc
            - name: NAMESPACE
              value: small-indie-bot
            - name: SHARE_DIR
              value: /mnt/kafka
            - name: CLUSTER_ID
              value: oh-sxaDRTcyAr6pFRbXyzA
            - name: DEFAULT_REPLICATION_FACTOR
              value: '3'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '2'
          volumeMounts:
            - name: kafka-nfs-pvc
              mountPath: /mnt/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-nfs-pvc
        namespace: small-indie-bot
      spec:
        storageClassName: kafka-nfs-manual
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 20Gi
