---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: small-indie-bot
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: grafana-app
    image:
      repository: grafana/grafana
      tag: 10.3.3
    env:
      TZ: America/Toronto
    service:
      main:
        enabled: true
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        hosts:
          - host: grafana.local.tam.land
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: local-tamland-tls
            hosts:
              - grafana.local.tam.land
    persistence:
      data:
        enabled: true
        type: custom
        mountPath: /var/lib/grafana
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/small-indie-bot-grafana/data
