apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: small-indie-bot
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: grafana/grafana-enterprise
              tag: 12.1.1
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 3000
    persistence:
      data:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/small-indie-bot/grafana/data
        advancedMounts:
          app:
            app:
              - path: /var/lib/grafana
                readOnly: false
