apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maybe
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        serviceAccount:
          identifier: maybe-app
        containers:
          app:
            image: &image
              repository: ghcr.io/maybe-finance/maybe
              tag: 0.5.0
            envFrom: &envFrom
              - secret: maybe-configuration
      worker:
        enabled: true
        containers:
          worker:
            image: *image
            command: ["bundle", "exec", "sidekiq"]
            envFrom: *envFrom
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 16.9
            envFrom: *envFrom
      redis:
        enabled: true
        containers:
          redis:
            image:
              repository: redis
              tag: 8.0.1
    serviceAccount:
      maybe-app: {}
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 3000
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      redis:
        enabled: true
        controller: redis
        ports:
          http:
            port: 6379
    ingress:
      app:
        enabled: true
        hosts:
          - host: finance.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - finance.local.tam.land
    persistence:
      app:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/maybe/app
        advancedMounts:
          app:
            app:
              - path: /rails/storage
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/maybe/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
      redis:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/maybe/redis
        advancedMounts:
          redis:
            redis:
              - path: /data