---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: prowlarr-app
    podAnnotations:
      setGateway: "true"
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1802
    env:
      TZ: America/Toronto
    hostname: prowlarr
    ingress:
      main:
        enabled: true
        hosts:
          - host: "prowlarr.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/prowlarr/config
        mountPath: /config