apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: prometheus
      version: 27.41.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    server:
      name: server
      image:
        respository: quay.io/prometheus/prometheus
        tag: v3.7.1
      persistentVolume:
        enabled: true
        accessModes:
          - ReadWriteMany
        existingClaim: prometheus-server-pvc
    alertmanager:
      enabled: true
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-pushgateway:
      enabled: false
