apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: local-homerow-tls
  namespace: secrets
matchNamespace:
  - homerow
avoidNamespaces:
  - 'admin'
  - 'default'
  - 'kube-system'
data:
  valueFrom:
    secretKeyRef:
      name: local-homerow-tls
      namespace: admin
