apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: retrorepair.wiki-tls
  namespace: secrets
matchNamespace:
  - retro-repair
avoidNamespaces:
  - 'admin'
  - 'default'
  - 'kube-system'
data:
  valueFrom:
    secretKeyRef:
      name: retrorepair.wiki-tls
      namespace: admin
