apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: tamland-tls
  namespace: secrets
matchNamespace:
  - 'file-sharing'
avoidNamespaces:
  - 'admin'
  - 'default'
  - 'kube-system'
data:
  valueFrom:
    secretKeyRef:
      name: tamland-tls
      namespace: admin
