# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.2/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: medusajs
  namespace: homerow
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      imagePullSecrets:
       - name: image-pull-secret
    controllers:
      api:
        enabled: true
        containers:
          app:
            image:
              repository: ghcr.io/homerow-ca/homerow-backend
              tag: latest
            envFrom:
              - secret: medusajs-backend-configuration
      storefront:
        enabled: true
        containers:
          app:
            image:
              repository: ghcr.io/homerow-ca/homerow-storefront
              tag: latest
            envFrom:
              - secret: medusajs-storefront-configuration
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 17.5
            envFrom:
              - secret: medusajs-backend-postgres-configuration
      redis:
        enabled: true
        containers:
          redis:
            image:
              repository: redis
              tag: 8.0.2
    service:
      api:
        enabled: true
        controller: api
        primary: true
        ports:
          http:
            port: 9000
      storefront:
        enabled: true
        controller: storefront
        ports:
          http:
            port: 8000
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      redis:
        enabled: true
        controller: redis
        ports:
          http:
            port: 6379
    ingress:
      api:
        enabled: true
        hosts:
          - host: api.homerow.ca
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: api
        tls:
          - secretName: homerow-tls
            hosts:
              - api.homerow.ca
      storefront:
        enabled: true
        hosts:
          - host: homerow.ca
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: storefront
        tls:
          - secretName: homerow-tls
            hosts:
              - homerow.ca
    persistence:
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/homerow/medusajs-backend/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
