---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: image-pull-secret
  namespace: homerow
spec:
  template:
    type: kubernetes.io/dockerconfigjson
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/homerow-pull-secret
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: medusajs-backend-configuration
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/medusajs-backend
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: medusajs-backend-postgres-configuration
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/medusajs-backend-postgres
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: medusajs-storefront-configuration
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/medusajs-storefront
