apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - openclaw-configuration-secret.sops.yaml
  - openclaw-gateway-config-secret.sops.yaml
  - persistence.yaml

