apiVersion: v1
stringData:
    openclaw.json: ENC[AES256_GCM,data:KFaryOQLoMfE+QA3c/hwKFsjoO1ifLVJwAUsfYo82UYJDWl7+FQw/WGwR5ekt6BRfBP9GQkXTTPOjOD/hdKVpV8IhbxoJrlLRbdv,iv:HLhandXaSbQq7fznpaGqI9qi0AuJmVIXEeklv9Zqc1s=,tag:KOSjPKioU9b4cnBUvOLE/g==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: openclaw-gateway-config
    namespace: openclaw
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T06:16:08Z"
    mac: ENC[AES256_GCM,data:LgCKjBchhXX/o1wQXnOdbUYN2BoDUwkb0QbZrHyQbQSZpX4b4DI9eP5fye1ppQ/Nigbbx2TgqX74KpWJJMMp3FDp7O4807oFkJG2QCq/NkU0HFxj7r0IvghRo+WEFDsy8uQr/WtIHIMD3X9HbiOfMTwHdZ/SZ/IzN5iWRHW6BfI=,iv:jVU0Iu7TscsHszMAWlth9pF5WkSREuvVVLlfn5TryBg=,tag:DbdSmuLzoAJ3JAHRAHoYLA==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.1
