apiVersion: v1
data:
    openclaw.json: ENC[AES256_GCM,data:P5dBugboLEHLWzjf6J1GsK3QVu6uDeQZctw7RYLpnXVUr7utE0XbpLTbhdDsITc6mstEi9dMNIejYYDtT+gQGU8jUSQ65KW8ao401udrrMU2xRF/ypRxAMguaelGOSSmCLcdWjwEtbaQiw8t7pn8RP+u/3yK7Ru91VwWbXEWTLS4odYtZPRzMNl6XFZvQ+4QvV2FddkthksuPPrilK4ls6pWVvWc0j057ZcAhWH4p1LEfqcdRqAtUo7x+LXuzVaTj65RYTB19I1xOVdoAY41XCa6Bp0EKr7U8Ps8pZnruZ+Yk4KxECFMYuaNkyib13pef/SjXdeLtKvHmrIksvHSk0rKu8eM,iv:e8glEmyis+TyIV1jmwK3Gs/8tyNxAM4nELh7LrvepqQ=,tag:H1KYp39lhrtYmlUq3qU+Vg==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: openclaw-gateway-config
    namespace: openclaw
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T21:49:19Z"
    mac: ENC[AES256_GCM,data:1i0klCOcvBNU36VcqWOna7LyOx75vl/601hVPHJo0T9PM80FPCEXsGQE/ufY1BLKazeHv5KzKOyQzIGrkhiaTVTs6s7+Kz/LFmWagpkVoeLfxRL3thmxmPiCDWeA2ATpwMPMUzphDqDZ3ZfhUfJFCTkwZ5jVHUg8bYYtlxuhFzs=,iv:REZOK7z7kgqAl4tU1zOk8+wQB7F84UgEF044SwyLI7s=,tag:R9YhtGoP/2LYhMYTh+wRwQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.1
