apiVersion: v1
data:
    openclaw.json: ENC[AES256_GCM,data:0zEMHSSeLTqZIQWvgFGoTC5pjWiybIt1hLZt1dSAo1Hk/6X/FHPsGLuDe8Uyc3jxoLnuoR+3yvIrYI/fpOFmimphBafSf9R6jkAS,iv:8fODco9KOs6vTYoq8b4jJ9DIv2sIuhjoARPNMjT+Nzo=,tag:sM7f+zVEhSOZjXOB4F/VAA==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: openclaw-gateway-config
    namespace: openclaw
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T06:36:22Z"
    mac: ENC[AES256_GCM,data:EDla+ETdmOjhroKiEYdoXfxiywFP5sUIwHjbwVipMiglQK/wCDF8NilDuhl5AxyROPC9ytelyj5UQH0hxBUUjIqGqFMB2wZtIYeFRDi4Qsfu2PctBShIaCCK/NNwQSnqhdl6It18Ng3jK3AefNd4JJQQ9Y2Abl5LzGlb1jz6FL8=,iv:8JEbuA98u9Mum7//lh51X73qA7FmH0Rk2a4umS4HBb8=,tag:YiQ6WjY1BOMZz705l8qOnw==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.1
