apiVersion: v1
kind: PersistentVolume
metadata:
  name: druid-broker-nfs-pv
spec:
  storageClassName: druid-broker-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.tam.land
    path: "/nfs-share/druid-broker"
