---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: druid-operator
  namespace: small-indie-bot
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: chart/
      sourceRef:
        kind: GitRepository
        name: druid-operator
        namespace: flux-system
      interval: 5m
  values:
    env:
      DENY_LIST: "default,kube-system"
      RECONCILE_WAIT: "10s"
      WATCH_NAMESPACE: ""
    replicaCount: 1
    image:
      repository: datainfrahq/druid-operator
      pullPolicy: IfNotPresent
      tag: ""
    kube_rbac_proxy:
      image:
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        pullPolicy: IfNotPresent
        tag: "v0.13.1"
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10
    serviceAccount:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      name: "druid-operator-controller-manager"
    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 65532
      runAsUser: 65532
      runAsGroup: 65532
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    crd:
      enabled: true
      keep: true

