---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media-management
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: plex-app
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.7.5604-980a13e02
    env:
      TZ: America/Toronto
      ADVERTISE_IP: 192.168.0.155
      PLEX_PREFERENCE_1: "FriendlyName=Homeland Farm"
      PLEX_PREFERENCE_2: "EnableIPv6=0"
      PLEX_PREFERENCE_3: "LanNetworksBandwidth=192.168.0.0/16"
      PLEX_PREFERENCE_4: "TreatWanIpAsLocal=0"
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plex.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/plex/config
        mountPath: /config
      transcode:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/plex/transcode
        mountPath: /transcode
      tv:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/tv
        mountPath: /media/tv
      movies:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/movies
        mountPath: /media/movies
