apiVersion: v1
stringData:
    NC_USER: ENC[AES256_GCM,data:2gopIHo71jdhHuMd7FKjcttx64/kWcn9n+CDsDg=,iv:5C1utSRWn3ZLQTux3ngaRdYopROFbtq0PaA6/OdEZt4=,tag:ARKB3YIbWr0rjERpjivOMg==,type:str]
    NC_PASSWORD: ENC[AES256_GCM,data:2ndtBH8U6dJ1KhiFptLEedtwDgbqrD7CdPsgFbBUt5g=,iv:tYzHHJpOiA6rse5HkHoTgbxBjukB3VxaDCtVUgiLQ00=,tag:RCHhY73BamHH0C93pih1wQ==,type:str]
    NC_URL: ENC[AES256_GCM,data:klXNK2BVgzjROepPs/3hAXcZnMwwsyVOsL4=,iv:Ub0BQpMGPaDjbCEQeYSU7atM8DtDcr4L4Lz9JlPVOrE=,tag:r2FOquqUFM+HVzOzFmJG/w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-sync-configuration
    namespace: miscellaneous
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-04-21T05:24:12Z"
    mac: ENC[AES256_GCM,data:POIeF2lQxwihan7WTZf7Xso8AanPt/f2gBSPtyahFYpdaxKhP9uy82O4mTofrmaFjRLyNa87rKIA7Aei+SkuNR8O/nNJTCmE62d8OmijWydBzWd8lmqnD9iSvs1NuyvErhOgAtRy8ALgqxRTjL/gXAo8kmYMB0Mw8uREuv2dW9I=,iv:3oiHe8wfn5bSp8PGOBCNCSnjkblL6Duq/BUKsPZWfac=,tag:Cq3MpKHQw6pGPTvPyS3Geg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
