---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-sync
  namespace: cert-manager
  labels:
    app: cert-manager-sync
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-sync
      version: v1
  template:
    metadata:
      labels:
        app: cert-manager-sync
        version: v1
    spec:
      serviceAccountName: cert-manager-sync-app
      imagePullSecrets:
        - name: regcred
      containers:
        - image: registry.local.tam.land/cert-manager-sync/cert-manager-sync:0.0.1
          name: cert-manager-sync
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
