apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sylv-text-thing
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: registry.local.tam.land/wow/sylvtextthing
              tag: latest
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        hosts:
          - host: sylv.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
              - sylv.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/sylvtextthing/app
        advancedMounts:
          app:
            app:
              - path: /app/database
                readOnly: false
