---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sylv-text-thing
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: registry.local.tam.land/wow/sylvtextthing
              tag: latest
    serviceAccount:
      create: true
      name: sylvtextthing-app
    service:
      main:
        enabled: true
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        hosts:
          - host: sylv.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - secretName: tamland-tls
            hosts:
              - sylv.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/sylvtextthing
        globalMounts:
          - path: /app/database
            readonly: false
