---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: image-pull-secret
  namespace: homerow
spec:
  template:
    type: kubernetes.io/dockerconfigjson
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/homerow-pull-secret
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ecommerce-uat-postgres-configuration
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/ecommerce-uat-postgres
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ecommerce-uat-jwt-key
  namespace: homerow
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/homerow/ecommerce-uat-jwt-key
