---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homerow-ecommerce-uat
  namespace: homerow
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecommerce-uat
  namespace: homerow
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      imagePullSecrets:
       - name: image-pull-secret
    serviceAccount:
      homerow-ecommerce-uat:
        enabled: true
    controllers:
      app:
        enabled: true
        pod:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-pre-populate: 'true'
            vault.hashicorp.com/role: 'homerow-ecommerce-uat-role'
            vault.hashicorp.com/agent-inject-secret-config.yaml: 'secrets/homerow/ecommerce-uat-config'
            vault.hashicorp.com/agent-inject-file-config.yaml: 'config.yaml'
            vault.hashicorp.com/agent-inject-template-config.yaml: |
              {{- with secret "secrets/homerow/ecommerce-uat-config" -}}
              database_url: {{ .Data.data.database_url | printf "%q" }}
              apalis_database_url: {{ .Data.data.apalis_database_url | printf "%q" }}
              site_url: {{ .Data.data.site_url | printf "%q" }}
              images_dir: {{ .Data.data.images_dir | printf "%q" }}
              jwt_key_path: {{ .Data.data.jwt_key_path | printf "%q" }}

              github_oauth:
                client_id: {{ .Data.data.github_oauth.client_id | printf "%q" }}
                client_secret: {{ .Data.data.github_oauth.client_secret | printf "%q" }}
                redirect_url: {{ .Data.data.github_oauth.redirect_url | printf "%q" }}

              google_oauth:
                client_id: {{ .Data.data.google_oauth.client_id | printf "%q" }}
                client_secret: {{ .Data.data.google_oauth.client_secret | printf "%q" }}
                redirect_url: {{ .Data.data.google_oauth.redirect_url | printf "%q" }}

              discord_oauth:
                client_id: {{ .Data.data.discord_oauth.client_id | printf "%q" }}
                client_secret: {{ .Data.data.discord_oauth.client_secret | printf "%q" }}
                redirect_url: {{ .Data.data.discord_oauth.redirect_url | printf "%q" }}

              discord_webhooks:
                contact_us: {{ .Data.data.discord_webhooks.contact_us | printf "%q" }}

              shippo:
                api_key: {{ .Data.data.shippo.api_key | printf "%q" }}
                from_address:
                  name: {{ .Data.data.shippo.from_address.name | printf "%q" }}
                  street1: {{ .Data.data.shippo.from_address.street1 | printf "%q" }}
                  city: {{ .Data.data.shippo.from_address.city | printf "%q" }}
                  state: {{ .Data.data.shippo.from_address.state | printf "%q" }}
                  zip: {{ .Data.data.shippo.from_address.zip | printf "%q" }}
                  country: {{ .Data.data.shippo.from_address.country | printf "%q" }}

              stripe:
                secret_key: {{ .Data.data.stripe.secret_key | printf "%q" }}
                webhook_key: {{ .Data.data.stripe.webhook_key | printf "%q" }}

              resend_key: {{ .Data.data.resend_key | printf "%q" }}
              {{- end -}}
        containers:
          app:
            image:
              repository: ghcr.io/homerow-ca/website
              tag: 0.0.5
              pullPolicy: Always
            command: ["/bin/sh","-c"]
            args:
              - |
                set -eu
                ln -sf /vault/secrets/config.yaml /app/config.yaml
                chmod 0400 /vault/secrets/config.yaml || true
                exec /app/homerow --tracing-level "DEBUG"
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 18.0
            envFrom:
              - secret: ecommerce-uat-postgres-configuration
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8080
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
    ingress:
      app:
        enabled: true
        hosts:
          - host: uat.homerow.ca
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: homerow-tls
            hosts:
              - uat.homerow.ca
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/homerow/ecommerce-uat/images
        advancedMounts:
          app:
            app:
              - path: /app/images
      jwt-key:
        enabled: true
        type: secret
        name: ecommerce-uat-jwt-key
        advancedMounts:
          app:
            app:
              - path: /app/jwt_key
                readOnly: true
                subPath: jwt_key   
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/homerow/ecommerce-uat/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql
