---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash-community
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.appscode.com/stable
      chart: stash-community
      version: v0.23.0
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'stash-role'
      vault.hashicorp.com/agent-inject-secret-stash-license.txt: 'secret/backups/stash-licenses'
      vault.hashicorp.com/agent-inject-template-stash-license.txt: |
        {{- with secret "secret/backups/stash-licenses" -}}
        {{ .Data.data.stashLicense }}
        {{- end -}}
    license: /vault/secrets/stash-license.txt
    serviceAccount:
      create: true
      name: stash-app
