---
# Source: erpnext/templates/job-create-site.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: frappe-bench-erpnext-new-site-20241222011247
  namespace: homerow
  labels:
    helm.sh/chart: erpnext-7.0.146
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: frappe-bench
    app.kubernetes.io/version: "v15.45.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      initContainers:
        - name: validate-config
          image: "frappe/erpnext:v15.48.2"
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - >
              export start=`date +%s`;
              until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
                [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
                [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
              do
                echo "Waiting for sites/common_site_config.json to be created";
                sleep 5;
                if (( `date +%s`-start > 600 )); then
                  echo "could not find sites/common_site_config.json with required keys";
                  exit 1
                fi
              done;
              echo "sites/common_site_config.json found";

              echo "Waiting for database to be reachable...";
              wait-for-it -t 180 $(DB_HOST):$(DB_PORT);
              echo "Database is reachable.";
          env:
            - name: "DB_HOST"
              value: erpnext-mariadb.homerow.svc.cluster.local
            - name: "DB_PORT"
              value: "3306"
          resources:
            {}
          securityContext:
            capabilities:
              add:
              - CAP_CHOWN
          volumeMounts:
            - name: sites-dir
              mountPath: /home/frappe/frappe-bench/sites
      containers:
      - name: create-site
        image: "frappe/erpnext:v15.48.2"
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          - >
            set -x;

            bench_output=$(bench new-site ${SITE_NAME} \
              --no-mariadb-socket \
              --db-type=${DB_TYPE} \
              --db-host=${DB_HOST} \
              --db-port=${DB_PORT} \
              --admin-password=${ADMIN_PASSWORD} \
              --mariadb-root-username=${DB_ROOT_USER} \
              --mariadb-root-password=${DB_ROOT_PASSWORD} \
              --install-app=erpnext \
             | tee /dev/stderr);

            bench_exit_status=$?;

            if [ $bench_exit_status -ne 0 ]; then
                # Don't consider the case "site already exists" an error.
                if [[ $bench_output == *"already exists"* ]]; then
                    echo "Site already exists, continuing...";
                else
                    echo "An error occurred in bench new-site: $bench_output"
                    exit $bench_exit_status;
                fi
            fi

            set -e;

            rm -f currentsite.txt
        env:
          - name: "SITE_NAME"
            value: "erp.local.homerow.ca"
          - name: "DB_TYPE"
            value: mariadb
          - name: "DB_HOST"
            value: erpnext-mariadb.homerow.svc.cluster.local
          - name: "DB_PORT"
            value: "3306"
          - name: "DB_ROOT_USER"
            value: "root"
          - name: "DB_ROOT_PASSWORD"
            value: #REDACTED
          - name: "ADMIN_PASSWORD"
            value: #REDACTED
        resources:
          {}
        securityContext:
          capabilities:
            add:
            - CAP_CHOWN
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext-worker-pvc
            readOnly: false
        - name: logs
          emptyDir: {}
