---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chia-blockchain
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://anthonytam.github.io/blockchain-helm-charts/helm
      chart: chia-blockchain
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: blockchain-charts
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'chia-role'
      vault.hashicorp.com/agent-inject-secret-key.txt: 'secret/crypto/chia'
      vault.hashicorp.com/agent-inject-template-key.txt: |
        {{- with secret "secret/crypto/chia" -}}
        {{ .Data.data.key }}
        {{- end -}}
    serviceAccount:
      create: true
      name: chia-app
    image:
      repository: ghcr.io/chia-network/chia
      tag: 1.5.1
    env:
      TZ: America/Toronto
      keys: /vault/secrets/key.txt
    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "crypto-sharing"
        type: LoadBalancer
    persistence:
      key:
        enabled: false
      blockchain:
        enabled: true
        storageClass: esxi01-storage-class
        accessMode: ReadWriteOnce
        size: 300Gi
        mountPath: /root/.chia
      plots:
        enabled: false
