---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chia-blockchain
  namespace: crypto
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      chia-blockchain: {}
    controllers:
      app:
        pod:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'chia-role'
            vault.hashicorp.com/agent-inject-secret-key.txt: 'secrets/crypto/chia'
            vault.hashicorp.com/agent-inject-template-key.txt: |
              {{- with secret "secrets/crypto/chia" -}}
              {{ .Data.data.key }}
              {{- end -}}
        serviceAccount:
          identifier: chia-blockchain
        containers:
          app:
            image:
              repository: ghcr.io/chia-network/chia
              tag: 2.5.4
            env:
              TZ: America/Toronto
              keys: /vault/secrets/key.txt
    service:
      app:
        controller: app
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.2
          metallb.universe.tf/allow-shared-ip: "crypto-sharing"
        ports:
          p2p:  
            enabled: true
            port: 8444
            protocol: TCP
          farmer:
            enabled: true
            port: 8447
            protocol: TCP
    persistence:
      blockchain:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/crypto/chia/blockchain
        advancedMounts:
          app:
            app:
              - path: /root/.chia
      plots: 
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/chia-plots
        advancedMounts:
          app:
            app:
              - path: /plots
