---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: torrent-app
    podAnnotations:
      setGateway: "true"
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
    settings:
      automaticPortSetup: true
    env:
      TZ: America/Toronto
    hostname: qbittorrent
    ingress:
      main:
        enabled: true
        hosts:
          - host: "qbittorrent.homeland.farm"
            paths:
              - path: /
                pathType: Prefix
    service:
      bittorent:
        enabled: true
        type: ClusterIP
        ports:
          bittorrent:
            enabled: true
            port: 6881
            protocol: TCP
            targetPort: 6881
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/qbittorrent/config
        mountPath: /config
      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/mammoth/complete
        mountPath: /complete
      downloads:
        enabled: true
        type: hostPath
        hostPath: /var/local/kubernetes/media/qbittorrent/temp
        mountPath: /downloads