---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: retro-repair
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: wikijs
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: retro-repair-wikijs-app
    image:
      repository: linuxserver/wikijs
      tag: 2.5.297
    env:
      TZ: America/Toronto
    envFrom:
      - secretRef:
          name: wikijs-crdentials
    ingress:
      main:
        enabled: true
        hosts:
          - host: retrorepair.wiki
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: retrorepair.wiki-tls
            hosts:
              - retrorepair.wiki
    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/wikijs
