apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: paperless-ngx-app
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.5.3
            envFrom: &envFrom
              - secret: paperless-configuration
      redis:
        containers:
          main:
            image:
              repository: redis
              tag: 7.2.4
    service:
      main:
        controller: main
        ports:
          http:
            port: 8000
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      main:
        enabled: true
        hosts:
          - host: paperless.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - secretName: local-tamland-tls
            hosts:
              - paperless.local.tam.land

    persistence:
      data:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/data
        globalMounts:
          - path: /usr/src/paperless/data
      media:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/media
        globalMounts:
          - path: /usr/src/paperless/media
      export:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/export
        globalMounts:
          - path: /usr/src/paperless/export
      consume:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/consume
        globalMounts:
          - path: /usr/src/paperless/consume
