# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.1.2/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.17.1
            envFrom: &envFrom
              - secret: paperless-configuration
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 16.9
            envFrom: *envFrom
      redis:
        enabled: true
        containers:
          redis:
            image:
              repository: redis
              tag: 8.0.3
      ai:
        enabled: true
        containers:
          ai:
            image:
              repository: clusterzx/paperless-ai
              tag: 3.0.7
            envFrom: *envFrom
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8000
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      redis:
        enabled: true
        controller: redis
        ports:
          http:
            port: 6379
      ai:
        enabled: true
        controller: ai
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        hosts:
          - host: paperless.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - paperless.local.tam.land
      ai:
        enabled: true
        hosts:
          - host: paperless-ai.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: ai
        tls:
          - secretName: local-tamland-tls
            hosts:
              - paperless-ai.local.tam.land
    persistence:
      consume:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/paperless/consume
        advancedMounts:
          app:
            app:
              - path: /usr/src/paperless/consume
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/paperless/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
      ai:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/paperless/ai
        advancedMounts:
          ai:
            ai:
              - path: /app/data

