apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: paperless-ngx-app
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.15.3
            envFrom: &envFrom
              - secret: paperless-configuration
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 16.9
            envFrom: *envFrom
      redis:
        containers:
          app:
            image:
              repository: redis
              tag: 8.0.1
    service:
      app:
        controller: app
        ports:
          http:
            port: 8000
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      app:
        enabled: true
        hosts:
          - host: paperless.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - paperless.local.tam.land

    persistence:
      data:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/data
        advancedMounts:
          app:
            app:
              - path: /usr/src/paperless/data
      media:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/media
        advancedMounts:
          app:
            app:
              - path: /usr/src/paperless/media
      export:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/export
        advancedMounts:
          app:
            app:
              - path: /usr/src/paperless/export
      consume:
        enabled: true
        type: nfs
        server: truenas.local.tam.land
        path: /mnt/main-bay/k8s-data/paperless/consume
        advancedMounts:
          app:
            app:
              - path: /usr/src/paperless/consume
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/paperless/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                readOnly: false

