---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: paperless-configuration
  namespace: other-webapps
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/other-webapps/paperless
