---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-general
  namespace: database
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.9.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: database-app
    global:
      storageClass: esxi01-storage-class
      auth:
        existingSecret: postgres-credentials
        secretKeys:
          adminPasswordKey: admin-password
    image:
      repository: bitnami/postgresql
      tag: 14.5.0-debian-11-r14
