---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-general
  namespace: database
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 12.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: database-app
    auth:
      existingSecret: postgres-credentials
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
    primary:
      persistence:
        enabled: true
        existingClaim: postgres-pvc
    image:
      repository: bitnami/postgresql
      tag: 14.5.0-debian-11-r14
