apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs-pv
spec:
  storageClassName: postgres-nfs-manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.tam.land
    path: "/nfs-share/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-nfs-pvc
  namespace: database
spec:
  storageClassName: postgres-nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
