---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner-k8s-data
  namespace: csi
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: k8s-sigs
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: nfs-k8s-data-csi
    nfs:
      server: truenas.local.tam.land
      path: /mnt/main-bay/k8s-data
    storageClass:
      create: true
      defaultClass: false
      name: nfs-k8s-data
      reclaimPolicy: Retain
