---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: dxflrs/garage
              tag: v2.1.0
    service:
      s3:
        enabled: true
        controller: app
        primary: true
        ports:
          s3:
            port: 3900
      app:
        enabled: true
        controller: app
        ports:
          web:
            port: 3902
    ingress:
      app:
        enabled: true
        hosts:
          - host: garages3.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - garages3.local.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/admin/garage/config
        advancedMounts:
          app:
            app:
              - path: /etc/garage.toml
                readOnly: false
                subPath: garage.toml
      meta:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/admin/garage/meta
        advancedMounts:
          app:
            app:
              - path: /var/lib/garage/meta
      data:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/admin/garage/data
        advancedMounts:
          app:
            app:
              - path: /var/lib/garage/data
