apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - cilium.yaml
  - csi-driver-smb.yaml
  - factorio-helm.yaml
  - grafana.yaml
  - hashicorp.yaml
  - jameswynn.yaml
  - jetstack.yaml
  - mss.yaml
  - nvidia-gpu-cloud.yaml
  - prometheus-community.yaml
  - traefik.yaml
  - zabbix-community.yaml
