---
apiVersion: v1
kind: Secret
metadata:
  name: homelandfarm-tls
  namespace: admin
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "homelandfarm-cert"
  namespace: admin
spec:
  secretName: "homelandfarm-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "homeland.farm"
  dnsNames:
    - "homeland.farm"
    - "*.homeland.farm"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: homelandfarm-tlsstore
  namespace: admin
spec:
  defaultCertificate:
    secretName: "homelandfarm-tls"
