---
apiVersion: v1
kind: Secret
metadata:
  name: local-homerow-tls
  namespace: admin
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "local-homerow-cert"
  namespace: admin
spec:
  secretName: "local-homerow-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "local.homerow.ca"
  dnsNames:
    - "local.homerow.ca"
    - "*.local.homerow.ca"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: local-homerow-tlsstore
  namespace: admin
spec:
  defaultCertificate:
    secretName: "local-homerow-tls"
