---
apiVersion: v1
kind: Secret
metadata:
  name: local-tamland-tls
  namespace: admin
  annotations:
    cert-manager-sync.lestak.sh/sync-enabled: "true"
    cert-manager-sync.lestak.sh/vault-addr: "http://hashicorp-vault.secrets.svc.cluster.local:8200"
    cert-manager-sync.lestak.sh/vault-role: "cert-manager-sync-role"
    cert-manager-sync.lestak.sh/vault-auth-method: "kubernetes"
    cert-manager-sync.lestak.sh/vault-path: "le-certs/local-tam-land/certificate"
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "local-tamland-cert"
  namespace: admin
spec:
  secretName: "local-tamland-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "local.tam.land"
  dnsNames:
    - "local.tam.land"
    - "*.local.tam.land"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: local-tamland-tlsstore
  namespace: admin
spec:
  defaultCertificate:
    secretName: "local-tamland-tls"
