---
apiVersion: v1
kind: Secret
metadata:
  name: retrorepair.wiki-tls
  namespace: admin
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "retorepairwiki-cert"
  namespace: admin
spec:
  secretName: "retrorepair.wiki-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "retrorepair.wiki"
  dnsNames:
    - "retrorepair.wiki"
    - "*.retrorepair.wiki"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: retrorepairwiki-tlsstore
  namespace: admin
spec:
  defaultCertificate:
    secretName: "retrorepair.wiki-tls"
