apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: proxmox-data-ssd-array
  resources:
    requests:
      storage: 300Gi