apiVersion: v1
kind: Secret
metadata:
  name: logstash-pipelines
stringData:
  pipelines.yml: |-
    - pipeline.syslog: main
      config.string: |
        input {
          syslog {
            port => 51514
          }
        }
        filter {
          grok {
            match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
          }
          mutate {
            add_field => { "[@metadata][target_index]" => "prod-%{+YYYY.MM.dd}" }
          }
        }
        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            index => "%{[@metadata][target_index]}"
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
