---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: minio-app
    image:
      repository: minio/minio
      tag: RELEASE.2024-08-03T04-33-23Z
    args:
      - server
      - /data
      - --console-address
      - :9001
    service:
      main:
        enabled: true
        ports:
          http:
            port: 9001
          api:
            enabled: true
            port: 9000
    ingress:
      main:
        enabled: true
        hosts:
          - host: s3.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
          - host: minio.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
        tls:
          - secretName: local-tamland-tls
            hosts:
              - s3.local.tam.land
              - minio.local.tam.land
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /root/.minio
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/minio-s3/config
      data:
        enabled: true
        type: custom
        mountPath: /data
        volumeSpec:
          nfs:
            server: nfs.local.tam.land
            path: /nfs-share/minio-s3/data
