apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alloy-gateway-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-ssd-array
  resources:
    requests:
      storage: 5Gi