apiVersion: v1
stringData:
    garage.toml: ENC[AES256_GCM,data:z+/VdHmaIgJg8U4rdaABxgjABoGceR+o1RXjTBQfyq7HYPxXdBmsRPGoJ6d26Kfu8ReGxvgtM3m+nm0PAMRZTqDIPJr3EnuU2jrKW9IcwOC8NIfR3LlDUcpzKeXn+lyfn01y4mKcqbZlronA6YEMi4lgB86H/WDBJ2qfTRJ/UdoO5Ak7YWxGEy00+o48/SEFQ/YGaDUb5dixP5ZkbZ2yYLUrT4EvRy1yQLBJjUWGnWqISS7vSAQh2KTpubod86nx/mvGpsmru6ksTonEHuno46ev6/8uHGStIRzU6X/ppJIT8155X3v1ORL8VyLwKxEtd7FJ6ls7MTTCV9GPRnYPEMumUkpIZNzNADKoWtAIs/nEYPw8g3H4kwsHk4PW6D8+nnwrO2i/rHKVXfbgAhBR4qtjoHutOf58lRcMFiCIdG8B0H5OQPXldrAxsyiQmyKjq7Hmpa5YEgDPuUOIhgXyM/324pDvPudauiCkz4wbXG8C2bR25UMSvZE1rR/Hg4fTzLJbzEvXJ4L1iTWBrIwx9n7bTn2wva5HW9MVgLCcHKUwGlUeC5BzCgTknAMDud/Sjbk7Qs/Fc1/5PK33Bm7EhGXjMsmaav6pwjkWxEDNnB/jufzE+S+2hBPgxO6HukCDYOQBHit9HUwDZxVdoJcAuZH5+VcozheDtzU8ggrv3fXq8HO+fbqsJuTrL0k5x8QUIDglROUaB5VuI04xFMnLxR58rym163zeznEBunrwm8g42e3hmpoapqXTxUEv4T4VZ8PidR+sLn+JwxphKn4=,iv:1ud69sE+hSccVi/waWHT2k8MXH5zqfdELszXgctzChE=,tag:p/WvgydaK57l1qNYm0O2mg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: garage-configuration
    namespace: admin
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T00:32:04Z"
    mac: ENC[AES256_GCM,data:g9yO1uaBu0uRxABPI5mv7lfhh2g2lTFpy1xGjfs7qtnVepQ7OezAlEc45kv6aGUtcceBtxRc5zowUl7qDBexVhv1znp2fp1wiFYoDq6yyBWjBtP/o8ZEJ6Zv1MuMhML9Of7UsuC/t5Nq1VPjAkt8DaxOJKRv5Fm0fHwqlFqShFQ=,iv:i9cvwsUIDIOoDoJpBRQxaNa2S5kLm6TIEaWm07ex4UM=,tag:lT1FMwHx9toYH7rCxtLH9Q==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    version: 3.13.3
