---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: file-sharing
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: nextcloud
      version: 4.3.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud-helm
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      enabled: true
      serviceaccount:
        create: true
        name: nextcloud-app
    image:
      repository: nextcloud
      tag: 27.1.1-apache
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      existingClaim: nextcloud-nfs-pvc
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data-nfs-pvc
    ingress:
      enabled: true
      annotations: {}
      tls:
        - secretName: tamland-tls
          hosts:
          - cloud.tam.land
      labels: {}
      path: /
      pathType: Prefix
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres-general-postgresql.database.svc:5432
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: postgres-username
        passwordKey: postgres-password
    nextcloud:
      host: cloud.tam.land
    phpClientHttpsFix:
      enabled: true
    cronjob:
      enabled: true
    # Temp solution from Issue #10 to prevent installation failures
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
