---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: nextcloud-credentials
  namespace: file-sharing
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secret/webapps/data/nextcloud
