apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-data-pv
spec:
  storageClassName: nextcloud-data-nfs-manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: truenas.local.tam.land
    path: "/mnt/main-bay/k8s-data/nextcloud-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-nfs-pvc
  namespace: file-sharing
spec:
  storageClassName: nextcloud-data-nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
