apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: file-sharing
spec:
  storageClassName: nfs-k8s-data
  resources:
    requests:
      # "The provisioned storage limit is not enforced. The application can expand to use all the available storage regardless of the provisioned size."
      storage: 1Mi
  accessModes:
    - ReadWriteOnce
