---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ghostfolio-credentials
  namespace: other-webapps
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secret/webapps/data/ghostfolio
