# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.2/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ghostfolio
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ghostfolio/ghostfolio
              tag: 2.71.0
            envFrom: &envFrom
              - secret: ghostfolio-configuration
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 16.2
            envFrom: *envFrom
      redis:
        enabled: true
        containers:
          redis:
            image:
              repository: redis
              tag: 7.2.4
    serviceAccount:
      create: true
      name: ghostfolio-app
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 3333
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      redis:
        enabled: true
        controller: redis
        ports:
          http:
            port: 6379
    ingress:
      app:
        enabled: true
        hosts:
          - host: ghostfolio.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - ghostfolio.local.tam.land
    persistence:
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/ghostfolio/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                readOnly: false
