---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ghostfolio
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: ghostfolio/ghostfolio
              tag: 2.46.0
            envFrom:
              - secret: ghostfolio-configuration
    serviceAccount:
      create: true
      name: ghostfolio-app
    service:
      main:
        enabled: true
        ports:
          http:
            port: 3333
    ingress:
      main:
        enabled: true
        hosts:
          - host: ghostfolio.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - secretName: local-tamland-tls
            hosts:
              - ghostfolio.local.tam.land
