---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghostfolio
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://anthonytam.github.io/helm-charts/index
      chart: ghostfolio
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: anthonytam
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      create: true
      name: ghostfolio-app
    image:
      tag: 1.195.0
    env:
      BASE_CURRENCY: CAD
      DATABASE_URL: null
    service:
      main:
        enabled: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: portfolio.tam.land
            paths:
              - path: /
                pathType: Prefix
