---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ghostfolio
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ghostfolio/ghostfolio
              tag: 2.63.1
            envFrom:
              - secret: ghostfolio-configuration
      redis:
        enabled: true
        containers:
          redis:
            image:
              repository: redis
              tag: 7.2.4
    serviceAccount:
      create: true
      name: ghostfolio-app
    service:
      app:
        enabled: true
        controller: app
        ports:
          http:
            port: 3333
      redis:
        enabled: true
        controller: redis
        ports:
          http:
            port: 6379
    ingress:
      main:
        enabled: true
        hosts:
          - host: ghostfolio.local.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: app
        tls:
          - secretName: local-tamland-tls
            hosts:
              - ghostfolio.local.tam.land
