apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-qbittorent-pv
  namespace: media
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  local:
    path: /var/local/kubernetes/media/qbittorent
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker01.homeland.lan
