apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailrise
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: yoryan/mailrise
              tag: latest
    service:
      app:
        enabled: true
        controller: app
        primary: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.200.12.1
          metallb.universe.tf/allow-shared-ip: "misc-sharing"
        ports:
          smtp:
            enabled: true
            primary: true
            port: 8025
            protocol: TCP
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/admin/mailrise
        advancedMounts:
          app:
            app:
              - path: /etc/mailrise.conf
                subPath: mailrise.conf
    